import { GoogleGenAI } from "@google/genai";
import { GenerateImageOptions, GenerateImageResult } from '../types';

// Use the environment variable for the API key
const API_KEY = process.env.API_KEY || '';

// Nano Banana model alias
const MODEL_NAME = 'gemini-2.5-flash-image'; 

export async function generateImageFromDrawing(
  options: GenerateImageOptions
): Promise<GenerateImageResult> {
  try {
    if (!API_KEY) {
      return {
        success: false,
        error: 'API Key is missing. Please check your configuration.',
      };
    }

    const ai = new GoogleGenAI({ apiKey: API_KEY });

    const matches = options.imageData.match(/^data:(.+);base64,(.+)$/);
    if (!matches) {
      return {
        success: false,
        error: "Invalid image data format.",
      };
    }
    
    const mimeType = matches[1]; 
    const base64Data = matches[2];

    // Simplified prompt to be very direct
    const userInstruction = options.customPrompt 
      ? `Instruction: ${options.customPrompt}` 
      : "Instruction: Turn this sketch into a colorful, cute, 3D render style illustration for a children's book.";

    const promptText = `
You are a professional illustrator.
${userInstruction}
Output the result as an image.
`.trim();

    console.log(`Calling Gemini (${MODEL_NAME}) with prompt:`, promptText);

    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          // Sending image first is crucial for editing/transformation tasks
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data,
            },
          },
          {
            text: promptText,
          },
        ],
      },
      config: {
        safetySettings: [
          { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_ONLY_HIGH' },
        ]
      }
    });

    // Parse the response to find the generated image.
    const parts = response.candidates?.[0]?.content?.parts;

    if (!parts) {
      console.warn("Empty response parts from API", response);
      return {
        success: false,
        error: "No content generated by the model. Please try again.",
      };
    }

    // Iterate through parts to find the image
    let generatedImageBase64: string | undefined;
    let textResponse: string | undefined;

    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        const mime = part.inlineData.mimeType || 'image/png';
        generatedImageBase64 = `data:${mime};base64,${part.inlineData.data}`;
      }
      if (part.text) {
        textResponse = part.text;
      }
    }

    if (generatedImageBase64) {
      console.log("Image generation successful.");
      return {
        success: true,
        imageBase64: generatedImageBase64,
      };
    } else {
      console.error("Model returned text instead of image:", textResponse);
      return {
        success: false,
        error: textResponse || "The model did not return an image. It might have refused the request.",
      };
    }

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    return {
      success: false,
      error: error.message || "An unexpected error occurred during generation.",
    };
  }
}